services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    command: php-fpm -F
    volumes:
      - ./:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  reverb:
    build: .
    container_name: laravel_reverb
    restart: always
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - db
    networks:
      - laravel

  queue:
    build: .
    container_name: laravel_queue
    restart: always
    command: php artisan queue:work
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - db
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data: