services:
  app:
    build: .
    container_name: laravel_app
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  reverb:
    build: .
    container_name: laravel_reverb
    command: ["sh", "/var/www/script.sh"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - laravel

  queue:
    build: .
    container_name: laravel_queue
    command: ["sh", "/var/www/script.sh"]
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
